[project]
name = "test-referralsystemservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic==1.14.1",
    "asyncpg==0.30.0",
    "bcrypt==4.0.1",
    "fastapi==0.115.8",
    "fastapi-cache2[redis]==0.2.2",
    "flake8==7.1.1",
    "flake8-print==5.0.0",
    "passlib==1.7.4",
    "pre-commit==4.1.0",
    "pydantic-settings==2.7.1",
    "pydantic[email]==2.10.6",
    "pyjwt==2.10.1",
    "python-multipart==0.0.20",
    "pytz==2025.1",
    "uvicorn==0.34.0",
]
